name: finance_tracker
description: "Finance tracker test app DhiWise."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # FIREBASE
  firebase_core: ^2.25.4   # CORE
  firebase_auth: ^4.17.5   # Authentication
  cloud_firestore: ^4.15.5 # FIRESTORE / FIREBASE DB

  # STATE-MANAGEMENT
  provider: ^6.1.1

  # ANIMATION
  lottie: ^3.1.0

  # DATE-TIME
  intl: ^0.19.0

  # PIN-CODE/OTP
  pin_code_text_field: ^1.8.0 

  # GRID VIEW 
  flutter_staggered_grid_view: ^0.7.0 

  # SVG-ICONS 
  flutter_svg: ^2.0.10+1

  # INDICATOR 
  percent_indicator: ^4.2.3 

  # TimeLine 
  timelines: ^0.1.0 

  # TOAST 
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/icons/
    - asset/images/
    - asset/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: asset/fonts/Inter-Thin.ttf
          weight: 100
        - asset: asset/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/Inter-Light.ttf
          weight: 300
        - asset: asset/fonts/Inter-Regular.ttf
          weight: 400
        - asset: asset/fonts/Inter-Medium.ttf
          weight: 500
        - asset: asset/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Inter-Bold.ttf
          weight: 700
        - asset: asset/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Inter-Black.ttf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
